# File: Makefile
# Simple make file to build the executable

TARGETS = branch_mispred
CC=gcc
CFLAGS = -g -Wall -O3 -save-temps
INCLUDE = -I/lib/modules/`uname -r`/build/include
LIBS = 

all: 
	./stage2.sh query.txt config.txt